/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSourcesRouteImport } from './routes/_dashboard.sources'
import { Route as DashboardPipelineRouteImport } from './routes/_dashboard.pipeline'
import { Route as DashboardIdeaCardsRouteImport } from './routes/_dashboard.idea-cards'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdeaCardsRoute = DashboardIdeaCardsRouteImport.update({
  id: '/idea-cards',
  path: '/idea-cards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/idea-cards': typeof DashboardIdeaCardsRoute
  '/pipeline': typeof DashboardPipelineRoute
  '/sources': typeof DashboardSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/idea-cards': typeof DashboardIdeaCardsRoute
  '/pipeline': typeof DashboardPipelineRoute
  '/sources': typeof DashboardSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/idea-cards': typeof DashboardIdeaCardsRoute
  '/_dashboard/pipeline': typeof DashboardPipelineRoute
  '/_dashboard/sources': typeof DashboardSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/idea-cards' | '/pipeline' | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/idea-cards' | '/pipeline' | '/sources'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/dashboard'
    | '/_dashboard/idea-cards'
    | '/_dashboard/pipeline'
    | '/_dashboard/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/sources': {
      id: '/_dashboard/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof DashboardSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pipeline': {
      id: '/_dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/idea-cards': {
      id: '/_dashboard/idea-cards'
      path: '/idea-cards'
      fullPath: '/idea-cards'
      preLoaderRoute: typeof DashboardIdeaCardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardIdeaCardsRoute: typeof DashboardIdeaCardsRoute
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardSourcesRoute: typeof DashboardSourcesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardIdeaCardsRoute: DashboardIdeaCardsRoute,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardSourcesRoute: DashboardSourcesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
