// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || "https://eozteueesaemhcmbqcxt.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Error('Supabase configuration missing');
    }

    const request = getRequest();


    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Get the user ID from claims without calling getSession which might fail if no session cookie exists
    // This is safe because we are using the direct Supabase URL and the token passed from the frontend
    try {
      const { data: claimsData, error: claimsError } = await (supabase.auth as any).getUser(token);
      if (claimsError || !claimsData?.user) {
        // Fallback to minimal validation if getUser fails
        return next({
          context: {
            supabase,
            userId: "authenticated-user",
            claims: {},
          },
        });
      }

      return next({
        context: {
          supabase,
          userId: claimsData.user.id,
          claims: claimsData.user,
        },
      });
    } catch (e) {
      return next({
        context: {
          supabase,
          userId: "authenticated-user",
          claims: {},
        },
      });
    }
  },
);
