// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = "https://klhcrdacefntzqwqwiiu.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_aITpoyEkEtU60jzenvS3ig_wCGXYVGz";

    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getSession();
    if (error || !data?.session) {
      // If session fetch fails, try simple claim verification as fallback
      const { data: claimsData, error: claimsError } = await (supabase.auth as any).getClaims(token);
      if (claimsError || !claimsData?.claims) {
        throw new Error('Unauthorized: Invalid token');
      }
      return next({
        context: {
          supabase,
          userId: claimsData.claims.sub,
          claims: claimsData.claims,
        },
      });
    }

    return next({
      context: {
        supabase,
        userId: data.session.user.id,
        claims: data.session.user,
      },
    });
  },
);
