// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = "https://eozteueesaemhcmbqcxt.supabase.co";
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  console.log(`[Supabase Admin] Initializing client with URL: ${SUPABASE_URL}`);
  if (!SUPABASE_SERVICE_ROLE_KEY) {
    console.error("[Supabase Admin] SUPABASE_SERVICE_ROLE_KEY is missing from process.env");
    throw new Error("SUPABASE_SERVICE_ROLE_KEY is missing. Please check your project secrets.");
  }
  
  if (SUPABASE_SERVICE_ROLE_KEY.startsWith('eyJ')) {
    console.warn("[Supabase Admin] SUPABASE_SERVICE_ROLE_KEY looks like a JWT. This might be an old format key.");
  } else if (SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_')) {
    console.log("[Supabase Admin] SUPABASE_SERVICE_ROLE_KEY uses the new 'sb_' format.");
  } else {
    console.warn("[Supabase Admin] SUPABASE_SERVICE_ROLE_KEY has an unknown format.");
  }


  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
